import = ["/home/adrian/.config/alacritty/themes/themes/onedark.yaml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "Fira Code Nerd Font"

[window]
opacity = 0.85
