import = ["/home/adrian/.config/alacritty/themes/themes/catppuccin_mocha.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = "Fira Code Nerd Font"

[window]
opacity = 0.85
